apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployflow-frontend
  namespace: deployflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: deployflow-frontend

  template:
    metadata:
      labels:
        app: deployflow-frontend

    spec:
      containers:
        - name: frontend
          image: ghcr.io/idhananjay14/deployflow-frontend:f7639aa8a1feceb770690e42ca317f089b40a1dd
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
