apiVersion: v1
kind: Service

metadata:
  name: deployflow-backend
  namespace: deployflow

spec:
  selector:
    app: deployflow-backend

  ports:
    - name: http
      port: 3000
      targetPort: 3000
