apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployflow-database

spec:
  replicas: 1

  selector:
    matchLabels:
      app: deployflow-database

  template:
    metadata:
      labels:
        app: deployflow-database

    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: deployflow-db-config
                  key: DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: deployflow-db-config
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deployflow-db-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: database-init
              mountPath: /docker-entrypoint-initdb.d/01-init.sql
              subPath: 01-init.sql

      volumes:
        - name: database-init
          configMap:
            name: deployflow-db-init
