apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: deployflow
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/idhananjay14/DeployFlow.git
    targetRevision: main
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: deployflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true