apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployflow-frontend
  namespace: deployflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: deployflow-frontend

  template:
    metadata:
      labels:
        app: deployflow-frontend

    spec:
      containers:
        - name: frontend
          image: ghcr.io/idhananjay14/deployflow-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
