apiVersion: v1
kind: Service

metadata:
  name: deployflow-backend
  namespace: deployflow
  labels:
    app: deployflow-backend

spec:
  selector:
    app: deployflow-backend

  ports:
    - name: http
      port: 3000
      targetPort: 3000
